export const promise = {
  PENDING: '_PENDING',
  REJECTED: '_REJECTED',
  FULFILLED: '_FULFILLED',
};

export const countryList = {
  FETCH_COUNTRIES_LIST: 'FETCH_LIST_OF_COUNTRIES',
  GET_COUNTRIES_LIST: 'GET_LIST_OF_COUNTRIES_CACHE',
  SET_COUNTRY: 'SET_CURRENT_COUNTRY',
};

export const radioStation = {
  FETCH_STATIONS_BY_COUNTRY: 'FETCH_STATIONS_BY_COUNTRY',
  GET_STATIONS_BY_COUNTRY: 'GET_STATIONS_BY_COUNTRY_CACHE',
  SET_GENRE: 'SET_CURRENT_GENRE',
  SET_STATION: 'SET_STATION',
};